### ISSUE TITLE
cy.login is not a function

### ISSUE THREAD

**Issue by mpearsonQA** [Intility/cypress-msal#3]
I followed setup instructions and when attempting to run a cypress test and getting the following error:
![image](https://user-images.githubusercontent.com/66080829/215878512-dc5d814a-d4a9-4b40-9e9e-9bff253ec987.png)

I did manually create a /plugins folder to house the needed index.js file given the change in Cypress 10. Thanks for you guidance on moving past this error!

**Comment by h3rmanj** [comment]
Hi!

The plugin file was removed in [Cypress 10](https://docs.cypress.io/guides/references/migration-guide#Plugins-File-Removed), so the plugin has to be set up through the `cypress.config.js` file.

I'll try and update the README tomorrow since it is currently based on Cypress 9. In the meantime, you could try to see if [this solution](https://github.com/Intility/cypress-msal/issues/2#issuecomment-1340785740) by @xec resolves the issue 😊

**Comment by h3rmanj** [comment]
You also have to import the command in `support/e2e` instead of `support/index` I think 😄

**Comment by h3rmanj** [comment]
@mpearsonQA I merged the updated getting started docs for Cypress 10, which hopefully resolves your issue 😊

**Comment by mpearsonQA** [comment]
Thank you for your patience. I was able to move past the issue I was having with the instructions above...including the change to the import location. Thank you for your quick response and help.

**Comment by h3rmanj** [comment]
Good to hear! Please reach out if you find something else 🙂
